# Generated by Django 3.2.6 on 2023-04-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id_examenMedico', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_examenMedico', models.CharField(max_length=50)),
                ('tipo_examenMedico', models.CharField(max_length=50)),
                ('fecha_examenMedico', models.DateField(null=True)),
                ('resultado_examenMedico', models.CharField(max_length=1000)),
            ],
        ),
    ]
