# Generated by Django 3.2.6 on 2023-04-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenMedico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenmedico',
            old_name='fecha_examenMedico',
            new_name='fecha_realizacion',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='id_examenMedico',
            new_name='id_Examen_Medico',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='nombre_examenMedico',
            new_name='nombre_Examen_Medico',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='resultado_examenMedico',
            new_name='resultado',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='tipo_examenMedico',
            new_name='tipo_Examen_Medico',
        ),
    ]
