# Generated by Django 3.2.6 on 2023-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('id_historia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fechaCreacion_historia_clinica', models.CharField(max_length=50)),
                ('fechaUltimaActualizacion_historia_clinica', models.CharField(max_length=50)),
                ('descripcion_historia_clinica', models.CharField(max_length=2000)),
            ],
        ),
    ]
