# Generated by Django 3.2.6 on 2023-03-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_historia', models.CharField(max_length=10)),
                ('fechaCreacion', models.CharField(max_length=50)),
                ('fechaUltimaActualizacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=2000)),
            ],
        ),
    ]
