# Generated by Django 3.2.6 on 2023-03-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historia_Clinica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historia_clinica',
            old_name='descripcion_historia_clinica',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='historia_clinica',
            old_name='fechaCreacion_historia_clinica',
            new_name='fecha_Creacion',
        ),
        migrations.RenameField(
            model_name='historia_clinica',
            old_name='fechaUltimaActualizacion_historia_clinica',
            new_name='fecha_Ultima_Actualizacion',
        ),
        migrations.RenameField(
            model_name='historia_clinica',
            old_name='id_historia',
            new_name='id_Historia_Clinica',
        ),
    ]
