# Generated by Django 3.2.6 on 2023-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia_Clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia_clinica',
            name='id',
        ),
        migrations.AlterField(
            model_name='historia_clinica',
            name='id_historia',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
