# Generated by Django 3.2.6 on 2023-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historia_Clinica', '0002_auto_20230317_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historia_clinica',
            old_name='descripcion',
            new_name='descripcion_historia_clinica',
        ),
        migrations.RenameField(
            model_name='historia_clinica',
            old_name='fechaCreacion',
            new_name='fechaCreacion_historia_clinica',
        ),
        migrations.RenameField(
            model_name='historia_clinica',
            old_name='fechaUltimaActualizacion',
            new_name='fechaUltimaActualizacion_historia_clinica',
        ),
    ]
