# Generated by Django 3.2.6 on 2023-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='fecha',
            new_name='fecha_consulta',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='hora',
            new_name='hora_consulta',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='sede',
            new_name='sede_consulta',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='tipo',
            new_name='tipo_consulta',
        ),
    ]
