# Generated by Django 3.2.6 on 2023-03-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0002_auto_20230318_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_Consulta',
            field=models.DateField(null=True),
        ),
    ]
