# Generated by Django 3.2.6 on 2023-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_completo_usuario', models.CharField(max_length=50)),
                ('tipo_identificacion_usuario', models.CharField(max_length=50)),
                ('identificacion_usuario', models.CharField(max_length=50)),
                ('email_usuario', models.CharField(max_length=50)),
                ('rol_usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
