# Generated by Django 3.2.6 on 2023-03-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('tipo_identificacion', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
    ]
