# Generated by Django 3.2.6 on 2023-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='email_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='id_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='identificacion',
            new_name='identificacion_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_completo',
            new_name='nombre_completo_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='rol_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_identificacion',
            new_name='tipo_identificacion_usuario',
        ),
    ]
