# Generated by Django 3.2.6 on 2023-03-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Historia_Clinica', '0001_initial'),
        ('Paciente', '0001_initial'),
        ('Profesional_Salud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede_consulta', models.CharField(max_length=50)),
                ('fecha_consulta', models.CharField(max_length=50)),
                ('hora_consulta', models.CharField(max_length=50)),
                ('tipo_consulta', models.CharField(max_length=50)),
                ('completada', models.BooleanField()),
                ('historia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Historia_Clinica.historia_clinica')),
                ('paciente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente')),
                ('profesional', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profesional_Salud.profesional_salud')),
            ],
        ),
    ]
