# Generated by Django 3.2.6 on 2023-03-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
        ('Procedimientos', '0001_initial'),
        ('Antecedentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('id_historia', models.CharField(max_length=10)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Paciente.paciente')),
                ('fechaCreacion_historia_clinica', models.CharField(max_length=50)),
                ('fechaUltimaActualizacion_historia_clinica', models.CharField(max_length=50)),
                ('descripcion_historia_clinica', models.CharField(max_length=2000)),
                ('antecedentes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Antecedentes.antecedentes')),
                ('procedimientos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Procedimientos.procedimientos')),
            ],
        ),
    ]
