# Generated by Django 3.2.6 on 2023-03-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procedimientos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimientos',
            old_name='descripcion_procedimiento',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='procedimientos',
            old_name='fecha_procedimiento',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='procedimientos',
            old_name='id_procedimiento',
            new_name='id_Procedimiento',
        ),
        migrations.RenameField(
            model_name='procedimientos',
            old_name='tipo_procedimiento',
            new_name='tipo_de_Procedimiento',
        ),
    ]
