# Generated by Django 3.2.6 on 2023-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Antecedentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedentes',
            old_name='descripcion',
            new_name='descripcion_antecedente',
        ),
    ]
