# Generated by Django 3.2.6 on 2023-03-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Antecedentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedentes',
            old_name='descripcion_antecedente',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='antecedentes',
            old_name='id_antecedente',
            new_name='id_Antecedente',
        ),
    ]
