# Generated by Django 3.2.6 on 2023-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(max_length=10)),
                ('fecha_nacimiento_paciente', models.CharField(max_length=15)),
                ('edad_paciente', models.IntegerField()),
                ('genero_paciente', models.CharField(max_length=20)),
                ('rh_paciente', models.CharField(max_length=5)),
                ('plan_paciente', models.CharField(max_length=40)),
                ('prioridad_paciente', models.CharField(max_length=20)),
            ],
        ),
    ]
