# Generated by Django 3.2.6 on 2023-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idUsuario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=50)),
                ('tipoIdentificacion', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('fecha_nacimiento_paciente', models.CharField(max_length=15)),
                ('edad_paciente', models.IntegerField()),
                ('genero_paciente', models.CharField(max_length=20)),
                ('rh_paciente', models.CharField(max_length=5)),
                ('plan_paciente', models.CharField(max_length=40)),
                ('prioridad_paciente', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
