# Generated by Django 3.2.6 on 2023-03-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='edad_paciente',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento_paciente',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='genero_paciente',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='idUsuario',
            new_name='id_Usuario',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombreCompleto',
            new_name='nombre_Completo',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='plan_paciente',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='prioridad_paciente',
            new_name='prioridad',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='rh_paciente',
            new_name='rh',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='tipoIdentificacion',
            new_name='tipo_Identificacion',
        ),
    ]
