# Generated by Django 3.2.6 on 2023-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='edad',
            new_name='edad_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='genero',
            new_name='genero_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='plan',
            new_name='plan_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='prioridad',
            new_name='prioridad_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='rh',
            new_name='rh_paciente',
        ),
    ]
