# Generated by Django 3.2.6 on 2023-03-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_auto_20230318_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre_Completo',
            field=models.CharField(max_length=100),
        ),
    ]
