# Generated by Django 3.2.6 on 2023-04-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenMedico', '0002_auto_20230411_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenmedico',
            old_name='nombre_Examen_Medico',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='tipo_Examen_Medico',
            new_name='tipo',
        ),
    ]
