# Generated by Django 3.2.6 on 2023-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id_procedimiento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_procedimiento', models.CharField(max_length=50)),
                ('fecha_procedimiento', models.CharField(max_length=25)),
                ('descripcion_procedimiento', models.CharField(max_length=2000)),
            ],
        ),
    ]
