# Generated by Django 3.2.6 on 2023-03-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='fecha_consulta',
            new_name='fecha_Consulta',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='historia',
            new_name='historia_Clinica',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='hora_consulta',
            new_name='hora_Consulta',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='profesional',
            new_name='profesional_Salud',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='sede_consulta',
            new_name='sede_Consulta',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='tipo_consulta',
            new_name='tipo_Consulta',
        ),
    ]
