# Generated by Django 3.2.6 on 2023-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional_Salud',
            fields=[
                ('id_profesional_salud', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('especialidad_profesional_salud', models.CharField(max_length=35)),
                ('sede_profesional_salud', models.CharField(max_length=30)),
                ('consultorio_profesional_salud', models.CharField(max_length=20)),
            ],
        ),
    ]
