# Generated by Django 3.2.6 on 2023-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesional_Salud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='consultorio',
            new_name='consultorio_profesional_salud',
        ),
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='especialidad',
            new_name='especialidad_profesional_salud',
        ),
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='sede',
            new_name='sede_profesional_salud',
        ),
    ]
