# Generated by Django 3.2.6 on 2023-03-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesional_Salud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='consultorio_profesional_salud',
            new_name='consultorio',
        ),
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='especialidad_profesional_salud',
            new_name='especialidad',
        ),
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='idUsuario',
            new_name='id_Usuario',
        ),
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='nombreCompleto',
            new_name='nombre_Completo',
        ),
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='sede_profesional_salud',
            new_name='sede',
        ),
        migrations.RenameField(
            model_name='profesional_salud',
            old_name='tipoIdentificacion',
            new_name='tipo_Identificacion',
        ),
    ]
